apiVersion: local.test/v1
kind: Stub
metadata:
  name: render-annotations
  {{- include "nubus-common.annotations.render" ( dict
    "values" .Values.additionalAnnotations
    "context" . )
    | nindent 2 }}
