apiVersion: local.test/v1
kind: Stub
metadata:
  name: render-annotations
  annotations:
    {{- include "nubus-common.annotations.entries" ( dict
      "values" ( list (.Values.ingress).annotations .Values.additionalAnnotations )
      "context" . )
      | nindent 4 }}
