# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

apiVersion: local.test/v1
kind: Stub
metadata:
  name: render-pull-secrets
spec:
  template:
    spec:
      {{- include "nubus-common.images.renderPullSecrets" . | nindent 6 }}
