# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: ../team-souvap/templates/repo-component
contact_email: johannes.bornhold.extern@univention.de
project_author: Team SouvAP Dev
project_copyright: 2023, Univention GmbH
project_name: Common Helm
project_slug: common-helm
project_url: https://git.knut.univention.de/univention/customers/dataport/upx/common-helm
