---

# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Adding values for a test case should be done by means of the testing
# infrastructure. Essentially it should lead to usage of the parameters
# "--values" or "--set" in the call to the "helm" utility.

global:
  smtp:
    auth:
      username: null

smtp:
  auth:
    username: "stub-values-username"
    password: null
    existingSecret:
      name: null
      keyMapping:
        password: null
