---
apiVersion: v2
name: common
description: Common utilities and fragments for Helm charts
home: https://git.knut.univention.de/univention/customers/dataport/upx/common-helm
type: library
version: 0.3.1

dependencies:
  # We inherit the common naming pattern and utility functions from the Bitnami
  # common chart. This one is widely adopted and a well known naming scheme.
  - name: "common"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^2.2.2"
