---

# SPDX-FileCopyrightText: 2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: common
description: Common utilities and fragments for Helm charts
home: https://git.knut.univention.de/univention/customers/dataport/upx/common-helm
type: library
version: 0.6.0
deprecated: true
annotations:
  deprecationReason: "Use nubus-common instead and move needed functionality over into it"

dependencies:
  # We inherit the common naming pattern and utility functions from the Bitnami
  # common chart. This one is widely adopted and a well known naming scheme.
  - name: "common"
    version: "^2.2.2"
    repository: "https://charts.bitnami.com/bitnami"

...
