---

# SPDX-FileCopyrightText: 2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: common
description: Common utilities and fragments for Helm charts
home: https://git.knut.univention.de/univention/customers/dataport/upx/common-helm
type: library
version: 0.6.0
deprecated: true
annotations:
  deprecationReason: "Use nubus-common instead and move needed functionality over into it"

# Temporarily vendored inside the repository because of tls problems in the pipeline:
# Error: could not download oci://registry-1.docker.io/bitnamicharts/common:
# failed to do request: Head "https://registry-1.docker.io/v2/bitnamicharts/common/manifests/2.30.0":
# tls: failed to verify certificate: x509: certificate signed by unknown authority

dependencies:
  # We inherit the common naming pattern and utility functions from the Bitnami
  # common chart. This one is widely adopted and a well known naming scheme.
  - name: "common"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "^2.2.2"

...
