{{- /*
common.utils.merge will merge two YAML templates and output the result.
This takes an array of three values:
- the top context
- the template name of the overrides (destination)
- the template name of the base (source)
*/}}
{{- define "common.utils.merge" -}}
{{- $overrides := fromYaml (include .overrides .) | default (dict ) -}}
{{- $tpl := fromYaml (include .base .) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}
