---

# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: nubus-common
description: Common utilities and fragments for Helm charts in Nubus
home: https://git.knut.univention.de/univention/customers/dataport/upx/common-helm
type: library
version: 0.1.0

dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "https://charts.bitnami.com/bitnami"
