---

# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: nubus-common
description: Common utilities and fragments for Helm charts in Nubus
home: https://git.knut.univention.de/univention/customers/dataport/upx/common-helm
type: library
version: 0.1.0

# Temporarily vendored inside the repository because of tls problems in the pipeline:
# Error: could not download oci://registry-1.docker.io/bitnamicharts/common:
# failed to do request: Head "https://registry-1.docker.io/v2/bitnamicharts/common/manifests/2.30.0":
# tls: failed to verify certificate: x509: certificate signed by unknown authority

dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
