# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

apiVersion: local.test/v1
kind: Stub
metadata:
  name: secrets-key
data:
  secretKey: {{
    include "nubus-common.secrets.key"
      ( dict
        "existingSecret" .Values.client.auth.existingSecret
        "key" "password"
      ) | quote }}
